DATE:4/07/2022                           ASSIGNMENT -I                                                   NAME:R.SRIMATHI
                                                                                                          BRANCH:AI&DS

Q.1)Write a function called show_stars(rows). If rows are 5, it should print the following:
*
**
***
****
*****

In [1]:
rows=int(input("enter the no.of rows:"))
print("the pyramid pattern of star at a given rows is: ")
for i in range (rows):
    for i in range(i+1):
        print("*",end=" ")
    print("\n")

enter the no.of rows:5
the pyramid psttern of star at a given rows is: 
* 

* * 

* * * 

* * * * 

* * * * * 



Q-2)Write a program to remove characters from a string starting from zero up to n and return a new string.

In [3]:
str=input("enter the string value: ")
n=int(input("enter the nth term to remove from string: "))
print("original value ",str)
new_str =  str.replace(str[:n]," ")
print("the new string after removal is: ",new_str)

enter the string value: srimathi
enter the nth term to remove from string: 3
original value  srimathi
the new string after removal is:   mathi


Q-3)Iterate the given list of numbers and print only those numbers which are divisible by 5

In [ ]:
list1 = []
for i in range(5):
    list1 = int(input("enter the elements: "))
    list1.append(num)
for i in list1:
    if i % 5 == 0:
        print(i)

Q-4)Write a program to find how many times substring “Hi” appears in the given string.    

In [73]:
string = 'Hi guys,this is srimathi'
sub_string = 'Hi'
results = 0
sub_len = len(sub_string)
for i in range(len(string)):
    if string[i:i+sub_len] == sub_string:
        results += 1
print (results)

1


Q-5)Print the following pattern
1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5

In [1]:
n =  int(input("enter the no.of rows: "))
for i in range (n+1):
    for j in range (1,i+1):
        print(i,end=" ")
    print("\n")

enter the no.of rows: 5


1 

2 2 

3 3 3 

4 4 4 4 

5 5 5 5 5 



                                                        TOPIC-LIST

q-6)Python program to interchange first and last elements in a list

In [8]:
def swapList(sl):
    n = len(sl) 
    temp = sl[0]
    sl[0] = sl[n - 1]
    sl[n - 1] = temp
    return sl
print("elements before swapping")
l = [10, 14, 5, 9, 56, 12]
print(l)
print("elements after swapping")
print(swapList(l))

elements before swapping
[10, 14, 5, 9, 56, 12]
elements after swapping
[12, 14, 5, 9, 56, 10]


Q-7)Python program to swap two elements in a list

In [71]:
def swapPositions(list, pos1, pos2):
    list[pos1], list[pos2] = list[pos2], list[pos1]
    return list
List = [23, 65, 19, 90]
pos1, pos2  = 1, 3
print(swapPositions(List, pos1-1, pos2-1))


[19, 65, 23, 90]


Q-8)Python | Ways to find length of list

In [12]:
list = [1,2,3,4,5,6,87,89,9,4,"sri","mathi","@gmail"]
print(len(list))

13


In [13]:
list1 = ["srimathi","mega",1,75,86,67,"leo"]
print("the number of elements in string : ",len(list1))

the number of elements in string :  7


Q-9)Maximum of two numbers in Python

In [18]:
list1=[256,564,78,56,23]
print(max(list1,key =lambda value: int(value)) )

564


Q-10)Minimum of two numbers in Python

In [19]:
valuesList = [256,564,624,324,763,]

print(min(valuesList, key=lambda value: int(value)) )


256


                                                TOPIC:STRING

Q-11)Python program to check whether the string is Symmetrical or Palindrome

In [5]:
num = int(input("enter the number: "))
temp =  num
rev = 0
while (num>0):
    digit = num%10
    rev =  rev*10+digit
    num = num//10
if (temp == rev):
    print("the number is palindrome: " ,format(temp))
else:
    print("the number is not palindrome")

enter the number: 234
the number is not palindrome


Q-12)Reverse words in a given String in Python

In [27]:
string = "hi guys,this is srimathi"
s = string.split()[::-3]
l = []
for i in s:
    l.append(i)
print(" ".join(l))

srimathi hi


Q-13)Ways to remove i’th character from string in Python

In [33]:
str = "srimathi"
print ("The original string is : " + str)
str1 = ""
  
for i in range(len(str)):
    if i != 7:
        str1 = str1 + str[i]
print ("The string after removal of i'th character : " + str1)

The original string is : srimathi
The string after removal of i'th character : srimath


                                               TOPIC:TUPLE

Q-14)Python program to Find the size of a Tuple

In [34]:
Tuple1 = ("A", 1, "B", 2, "C", 3)
Tuple2=("sri",1,56,86,"mathi")
Tuple3 = ((1, "sri"), ( 2, "mathi"), (3, "mega"), (4, "loshini"))
print(len(Tuple1))
print(len(Tuple2))
print(len(Tuple3))


6
5
4


Q-15)Python – Maximum and Minimum K elements in Tuple

In [76]:
sample_tuple = (98, 99, 0, 9, 10, 8)

print("The tuple is : ")
print(sample_tuple)

K = 2
print("The value of K has been initialized to ")
print(K)
my_result = []
sample_typle = list(sample_tuple)
temp = sorted(sample_tuple)

for idx, val in enumerate(temp):
   if idx < K or idx >= len(temp) - K:
      my_result.append(val)
my_result = tuple(my_result)

print("The result is : " )
print(my_result)

The tuple is : 
(98, 99, 0, 9, 10, 8)
The value of K has been initialized to 
2


TypeError: 'list' object is not callable

Q-16)Python – Sum of tuple elements

In [39]:
Tuple1 = (22,68,96,28,34)
print("Tuple elements are = ", Tuple1)

Tuplesum = sum(Tuple1)
print("The Sum of numTuple Tuple Items = ", Tuplesum)

Tuple elements are =  (22, 68, 96, 28, 34)
The Sum of numTuple Tuple Items =  248


                                        TOPIC:DICTIONARY

Q-17)Python | Sort Python Dictionaries by Key or Value

In [78]:
dict = {3:'mega' ,6:'vishali' ,4:'surendar' ,8:'kevin' ,1:'aishwarya' ,9:'siva' }  
 
key_sort= sorted(dict.keys())
print("Sorted keys",key_sort)  
  
value_sort= sorted(dict.items())
print("Sorted Values",value_sort)  

Sorted keys [1, 3, 4, 6, 8, 9]
Sorted Values [(1, 'aishwarya'), (3, 'mega'), (4, 'surendar'), (6, 'vishali'), (8, 'kevin'), (9, 'siva')]


Q-18)Python dictionary with keys having multiple inputs

In [41]:
my_dict = {}
a, b, c = 15, 26, 38
my_dict[a, b, c] = a + b - c
a, b, c = 5, 4, 11
my_dict[a, b, c] = a + b - c
print("The dictionary is :")
print(my_dict)

The dictionary is :
{(15, 26, 38): 3, (5, 4, 11): -2}


                                              TOPIC:SET 

Q-19)Find the size of a Set in Python

In [42]:
n = len({1, 2, 3, 4, 5})
  
print("The length of set is:", n)

The length of set is: 5


Q-20)Iterate over a set in Python

In [46]:
str = "SriMaThi"
for val in str:
    print(val)

S
r
i
M
a
T
h
i


                                                    TOPIC:MATRIX

Q-21)Python – Assigning Subsequent Rows to Matrix first row elements

In [87]:
trial_list = [[5, 0, 99], [2, 6, 9], [7, 4, 2], [0, 3, 9]]
  
# printing original list
print("The original list : " , str(trial_list))
  
# pairing each 1st col with next rows in Matrix
res = {trial_list[0][ele] :  trial_list[ele + 1] for ele in range(len(trial_list) - 1)}
  
# printing result 
print("The Assigned Matrix : " , str(res))

TypeError: 'str' object is not callable

Q-22)Adding and Subtracting Matrices in Python

In [61]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("Addition of two matrix")
print(np.add(A, B))
print("subtraction of two matrix")
print(np.subtract(A,B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
subtraction of two matrix
[[-3 -3]
 [-3 -3]]


                                            TOPIC:FUNCTIONS

Q-23)How to get list of parameters name from a function in Python?

In [62]:
import inspect
import collections

In [63]:
print(inspect.signature(collections.Counter))

(iterable=None, /, **kwds)


In [64]:
def fun(a, b):
    return a**b 
import inspect 
print(inspect.signature(fun)) 

(a, b)


In [66]:
import inspect
import collections

In [67]:
print(inspect.getargspec(collections.Counter))

ArgSpec(args=['self', 'iterable'], varargs=None, keywords='kwds', defaults=(None,))


C:\Users\Srimathi\AppData\Local\Temp\ipykernel_5196\2364366472.py:1: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  print(inspect.getargspec(collections.Counter))


In [68]:
def fun(a, b):
    return a**b 
import inspect 
print(inspect.getargspec(fun)) 

ArgSpec(args=['a', 'b'], varargs=None, keywords=None, defaults=None)


C:\Users\Srimathi\AppData\Local\Temp\ipykernel_5196\832359272.py:4: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
  print(inspect.getargspec(fun))


Q-24)How to Print Multiple Arguments in Python?

In [69]:
def func(name, num):
    print("Hello from ", name + ', ' + num)
  
  
func("srimathi", "17")

Hello from  srimathi, 17
